{
 "title": "2 Pacman",
 "time": { "from": "2024-02-20T18:44:05.514Z", "to": "2024-02-20T18:56:49.665Z" },
 "templating": {
  "list": [
   { "name": "Pacman", "query": "1,2,3,4,5,6,7,8" }
  ]
 },
 "panels": [
  {
   "title": "Total Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 23, "x": 0, "y": 1 } },
    {
     "title": "Tile Packet Rate (10s Means) ",
     "type": "text",
     "description": "packet count is every 1s. These values are the mean of those numbers over a 10s window",
     "gridPos": { "h": 1, "w": 5, "x": 0, "y": 2 },
     "options": {
      "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "Chip Packet Rate (Mean over last 10s) ",
     "type": "text",
     "description": "packet count is every 1s. These values are the mean of those numbers over a 10s window",
     "gridPos": { "h": 1, "w": 6, "x": 5, "y": 2 },
     "options": {
      "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "P$Pacman: IO Channel Packet Rate (Mean over last 10s)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 }
    },
    {
     "title": "Top 100 Chip Packets (Mean over last 15m)",
     "type": "table",
     "gridPos": { "h": 16, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel Packets (Mean over last 15m)",
     "type": "table",
     "gridPos": { "h": 16, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "T1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "T2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Tile 1",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "T3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "T4",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "Tile 3",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "4" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 18 } }
   ]
  },
  {
   "title": "Invalid Parity Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 23, "x": 0, "y": 2 } },
    {
     "title": "Invalid Parity %  (in 10s bars)",
     "type": "text",
     "gridPos": { "h": 1, "w": 5, "x": 0, "y": 3 },
     "options": {
      "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "Chip Invalid Count (mean over last 10s)",
     "type": "text",
     "gridPos": { "h": 1, "w": 6, "x": 5, "y": 3 },
     "options": {
      "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "IO Channel Invalid Count (Mean over last 15m)",
     "type": "table",
     "description": "Each tile has 4 io channels. Which channel will be used by a particular chip is decided by the Hydra Network. This panel indicates the packet rate by IO channel for the last 10s interval (per io channel, per tile) ",
     "gridPos": { "h": 4, "w": 5, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "total 1",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Chips Invalid Count (last 15m)",
     "type": "table",
     "gridPos": { "h": 16, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixels Invalid Count (last 15m)",
     "type": "table",
     "gridPos": { "h": 16, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Tile 1",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "Tile 3",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 23, "x": 0, "y": 19 } }
   ]
  },
  {
   "title": "ADC Mean and RMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
    {
     "title": "ADC Mean and RMS - by Tile",
     "type": "text",
     "gridPos": { "h": 1, "w": 11, "x": 0, "y": 4 },
     "targets": [
      {}
     ]
    },
    {
     "title": "ADC Mean Distribution - by Tile",
     "type": "text",
     "gridPos": { "h": 1, "w": 9, "x": 11, "y": 4 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Tile 1",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Tile 1",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Chip ADC (Mean over last 15m)",
     "type": "table",
     "gridPos": { "h": 16, "w": 4, "x": 19, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 19, "x": 0, "y": 12 } },
    {
     "title": "Tile 3",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "4" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "4" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 3",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "4" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel ADC (Mean over last 15m)",
     "type": "table",
     "gridPos": { "h": 16, "w": 4, "x": 19, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 } }
   ]
  },
  {
   "title": "FIFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean (over 10s) Shared FIFO > 1/2 and FULL",
     "type": "text",
     "gridPos": { "h": 1, "w": 10, "x": 0, "y": 4 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Max (over 15m) Shared FIFO FULL - by chip",
     "type": "text",
     "gridPos": { "h": 1, "w": 6, "x": 10, "y": 4 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Top 100: Shared FIFO > 1/2  (1s Max)",
     "gridPos": { "h": 14, "w": 4, "x": 18, "y": 4 }
    },
    {
     "title": "Tile 1",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "2" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 1 ",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 2",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Max (over 15m) single reading (i.e. not mean as above) Shared FIFO > 1/2 and FULL",
     "type": "text",
     "gridPos": { "h": 1, "w": 10, "x": 0, "y": 11 },
     "targets": [
      {}
     ]
    },
    { "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 } },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "1s Max FIFO > 1/2",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "1s Max FIFO Full",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 17, "x": 0, "y": 17 } },
    {
     "title": "Tile 3",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "3" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "4" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile 3",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Tile 4",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 14, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "Top 100: Shared FIFO Full  (1s Max)",
     "type": "table",
     "description": "FIFO Full is the fraction of times a particular chip's FIFO was full divided by the total number of observations in a 1s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 1s ratios over the last 15m.",
     "gridPos": { "h": 14, "w": 4, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" }
       ]
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "1s Max FIFO > 1/2",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "1s Max FIFO Full",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "1s Max FIFO > 1/2",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "1s Max FIFO Full",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$Pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 } }
   ]
  },
  { "title": "Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "gridPos": { "h": 10, "w": 4, "x": 0, "y": 5 } }
 ]
}