{
 "title": "3 Tile",
 "description": "Real Time raw data quality monitoring for DUNE ND 2x2 detector",
 "time": { "from": "2024-02-20T18:50:44.736Z", "to": "2024-02-20T18:58:12.218Z" },
 "templating": {
  "list": [
   { "name": "pacman", "label": "Pacman", "query": "1,2,3,4,5,6,7,8" },
   { "name": "tile", "label": "Tile", "query": "1,2,3,4,5,6,7,8" },
   {
    "name": "focus_chip",
    "label": "Focus Chip",
    "query": "11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110"
   },
   { "name": "row1", "query": "11,12,13,14,15,16,17,18,19,20" },
   { "name": "row2", "query": "21,22,23,24,25,26,27,28,29,30" },
   { "name": "row3", "query": "31,32,33,34,35,36,37,38,39,40" },
   { "name": "row4", "query": "41,42,43,44,45,46,47,48,49,50" },
   { "name": "row5", "query": "51,52,53,54,55,56,57,58,59,60" },
   { "name": "row6", "query": "61,62,63,64,65,66,67,68,69,70" },
   { "name": "row7", "query": "71,72,73,74,75,76,77,78,79,80" },
   { "name": "row8", "query": "81,82,83,84,85,86,87,88,89,90" },
   { "name": "row9", "query": "91,92,93,94,95,96,97,98,99,100" },
   {
    "name": "row10",
    "query": "101,102,103,104,105,106,107,108,109,110"
   }
  ]
 },
 "panels": [
  {
   "title": "Filter Table and Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tile $tile: Chip Filter Table  (mean or max over global time window)",
     "type": "table",
     "gridPos": { "h": 16, "w": 14, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Statistics (over global time window)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "Total Packet Rate by chip",
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Total Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 23, "x": 0, "y": 2 } },
    {
     "title": "Tile $tile Packet Rate (Mean over 10s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Chip Packets (Mean over last 15m)",
     "type": "table",
     "gridPos": { "h": 19, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel Packets (Mean over last 15m)",
     "type": "table",
     "gridPos": { "h": 19, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Packet Rate (Max over 10s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Chip Packets (Max over last 15m)",
     "type": "table",
     "gridPos": { "h": 19, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel Packets (Max over last 15m)",
     "type": "table",
     "gridPos": { "h": 19, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Chip Packet Rate  (mean over last 10s)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Chip Packet Rate  (Max over last 10s)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "limit": "100",
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 3, "x": 13, "y": 22 } },
    { "gridPos": { "h": 1, "w": 23, "x": 0, "y": 23 } },
    { "gridPos": { "h": 1, "w": 11, "x": 9, "y": 24 } }
   ]
  },
  {
   "title": "Pixel Map - Total Packet Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 23, "x": 0, "y": 3 } },
    {
     "title": "Mean (over 10s) of Packet Rate - by pixel",
     "type": "text",
     "gridPos": { "h": 1, "w": 23, "x": 0, "y": 4 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Chip $row1",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 5 },
     "repeat": "row1",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row1$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row2",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 13 },
     "repeat": "row2",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row2$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row3",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 21 },
     "repeat": "row3",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row3$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row4",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 29 },
     "repeat": "row4",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row4$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row5",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 37 },
     "repeat": "row5",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row5$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row6",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 45 },
     "repeat": "row6",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row6$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row7",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 53 },
     "repeat": "row7",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row7$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row8",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 61 },
     "repeat": "row8",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row8$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row9",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 69 },
     "repeat": "row9",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row9$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $row10",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2.4, "x": 0, "y": 77 },
     "repeat": "row10",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$row10$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 21, "x": 0, "y": 85 } }
   ]
  },
  {
   "title": "Invalid and Configuration Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 4 } },
    {
     "title": "INVALID PACKET RATES",
     "type": "text",
     "gridPos": { "h": 1, "w": 21, "x": 0, "y": 5 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Tile $tile: Mean Invalid % (10s intervals)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": " invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Invalid Count (mean over last 10s)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 7, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile:Top 100  Invalid Rate (15m mean)",
     "type": "table",
     "gridPos": { "h": 15, "w": 4, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel Packet Rate (15m Mean)",
     "type": "table",
     "gridPos": { "h": 16, "w": 5, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 5, "x": 0, "y": 13 } },
    {
     "title": "Tile $tile: Mean Invalid Packet Count (10s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Pacman $pacman IO Channel Invalid Count (Mean over last 15m",
     "type": "table",
     "description": "Each tile has 4 io channels. Which channel will be used by a particular chip is decided by the Hydra Network. This panel indicates the packet rate by IO channel for the last 10s interval (per io channel, per tile) ",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "total 1",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 5, "x": 11, "y": 21 } },
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 22 } },
    {
     "title": "CONFIGURATION PACKET RATES",
     "type": "text",
     "gridPos": { "h": 1, "w": 21, "x": 0, "y": 23 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Tile $tile: Config Ratio (per second)",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Config Count (max over last 10s)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 7, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "alias": "config",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile: Top 100 Config (15m max)",
     "type": "table",
     "gridPos": { "h": 15, "w": 4, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Top 100 Pixel Packets (15m Mean)",
     "type": "table",
     "gridPos": { "h": 15, "w": 5, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 5, "x": 0, "y": 31 } },
    {
     "title": "Tile $tile: Config Packet Count (per second)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 5, "x": 7, "y": 34 } },
    {
     "title": "IO Channel Config Count (Max over last 10s)",
     "type": "table",
     "description": "Each tile has 4 io channels. Which channel will be used by a particular chip is decided by the Hydra Network. This panel indicates the packet rate by IO channel for the last 10s interval (per io channel, per tile) ",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "total 1",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 21, "x": 0, "y": 39 } }
   ]
  },
  {
   "title": "FIFO Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 5 } },
    {
     "title": "Tile $tile: Shared FIFO > 1/2 (10s Mean)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Shared FIFO FULL (10s Mean)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 8, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 18, "x": 0, "y": 13 } },
    {
     "title": "P$pacman Tile $tile: Shared FIFO > 1/2 (10s Max)",
     "type": "stat",
     "description": "Shared FIFO > 1/2 is the fraction of times the FIFO was more than half full (but not completely full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the max chip-level ratio for each chip",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Top 100: Shared FIFO > 1/2  (1s Max)",
     "type": "table",
     "description": "FIFO Full is the fraction of times a particular chip's FIFO was full divided by the total number of observations in a 1s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 1s ratios over the last 15m.",
     "gridPos": { "h": 11, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile: Shared FIFO Full (10s Max)",
     "type": "stat",
     "description": "Shared FIFO Full is the fraction of times the FIFO was more than half full (but not completely full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the max chip-level ratio for each chip",
     "gridPos": { "h": 10, "w": 4, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Top 100: Shared FIFO Full  (1s Max)",
     "type": "table",
     "description": "FIFO Full is the fraction of times a particular chip's FIFO was full divided by the total number of observations in a 1s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 1s ratios over the last 15m.",
     "gridPos": { "h": 11, "w": 4, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 25 } },
    {
     "title": "Chip $focus_chip: Local FIFO > 1/2 (10s Mean)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 5, "x": 13, "y": 26 } },
    {
     "title": "Chip $focus_chip: Local FIFO Full (10s Mean)",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 8, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Full",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $focus_chip: Local FIFO > 1/2 (10s Max)",
     "type": "stat",
     "description": "Shared FIFO > 1/2 is the fraction of times the FIFO was more than half full (but not completely full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the max chip-level ratio for each chip",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100: Local FIFO > 1/2  (15m Max)",
     "gridPos": { "h": 10, "w": 4, "x": 4, "y": 33 }
    },
    {
     "title": "Chip $focus_chip: Local Full (10s Max)",
     "type": "stat",
     "description": "Shared FIFO > 1/2 is the fraction of times the FIFO was more than half full (but not completely full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the max chip-level ratio for each chip",
     "gridPos": { "h": 10, "w": 4, "x": 11, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100: Local FIFO Full   (15m Max)",
     "gridPos": { "h": 10, "w": 4, "x": 15, "y": 33 }
    },
    { "gridPos": { "h": 2, "w": 21, "x": 0, "y": 43 } }
   ]
  },
  {
   "title": "ADC Mean and RMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 22, "x": 0, "y": 6 } },
    {
     "title": "P$pacman Tile $tile: ADC Value mean and rms",
     "type": "candlestick",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: ADC Value (by chip)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 7, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile: ADC Mean Distribution",
     "type": "histogram",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 7 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile: Max ADC",
     "type": "table",
     "gridPos": { "h": 11, "w": 3, "x": 17, "y": 7 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel ADC (Max over last 15m)",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile: ADC RMS Distribution",
     "type": "histogram",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 17 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $focus_chip on P$pacman Tile $tile : ADC Value mean and rms",
     "type": "candlestick",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: ADC RMS (by chip)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 7, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman Tile $tile: Max ADC RMS",
     "type": "table",
     "gridPos": { "h": 11, "w": 3, "x": 17, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel ADC Value (Max over last 15m)",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 22, "x": 0, "y": 29 } }
   ]
  },
  {
   "title": "Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  { "gridPos": { "h": 1, "w": 6, "x": 0, "y": 7 } },
  { "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 } }
 ]
}