{
 "title": "3 Tile",
 "description": "Real Time raw data quality monitoring for DUNE ND 2x2 detector",
 "time": { "from": "2024-10-03T14:39:11.184Z", "to": "2024-10-03T14:52:31.897Z" },
 "templating": {
  "list": [
   { "name": "pacman", "label": "Pacman", "query": "1,2,3,4" },
   { "name": "tile", "label": "Tile", "query": "1,2,3,4,5,6,7,8,9,10" },
   {
    "name": "focus_chip",
    "label": "Focus Chip",
    "query": "11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tile $tile . P$pacman: Data Rate by chip (10s Mean)",
     "type": "timeseries",
     "description": "Mean over 10s of data rates (expressed as packet count per second) by chip. Y-axis is log base 2. Yellow / Red thresholds = 100 / 1k p/s",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_chip",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "T$tile . P$pacman: Top-100 Pixel Rates (5m Max)",
     "type": "table",
     "description": "Highest 100 Data Rates over the last 5m (expressed as # packets per second) by pixel for the chosen tile. Each value is a 10s Mean. Yellow / Red thresholds = 1 / 5 p/s",
     "gridPos": { "h": 15, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: ADC Mean Distribution - Pixel Level",
     "type": "histogram",
     "description": "Histogram shows distribution of Pixel-level ADC 10s mean values over the global time window. The bucket size is 1. ADC values are recorded using 8 bits. A value of 255 indicates the signal maxed out. Consistent 255 values (or consistent values below 5) may mean the threshold is set too high (or too low). Both problematic threshold cases could result in missing information. ",
     "gridPos": { "h": 11, "w": 4, "x": 14, "y": 1 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Config Rate (1s Mean)",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates_per_chip",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman : ADC Value mean and rms (10s Mean) - Pixel Level",
     "type": "candlestick",
     "description": "Green bars are centered at Pixel-level Mean ADC value, the top/bottom of the bars are at Mean +/- RMS. All values are calculated over a 10s window.  Red thresholds are <5 or > 254. Yellow threshold is  > 250",
     "gridPos": { "h": 13, "w": 5, "x": 14, "y": 12 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 11, "x": 0, "y": 16 } },
    {
     "title": "Tile $tile . P$pacman: Shared FIFO > 1/2 and Full (10s Max)",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. \"Shared\" FIFO is calculated at the chip level. This graph shows the mean chip level ratio for the entire system. This stacked bar chart shows the FIFO > 1/2 (but not completely full) as a blue bar. On top of the blue bar is FIFO full shown as a red bar. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Local FIFO > 1/2 and Full (10s Max)",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. \"Local\" FIFO is calculated at the pixel level. This graph shows the mean pixel level ratio for the entire system. This stacked bar chart shows the FIFO > 1/2 (but not completely full) as a blue bar. On top of the blue bar is FIFO full shown as a red bar. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Mean Invalid % (10s Mean)",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": " invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 13, "x": 0, "y": 25 } },
    { "gridPos": { "h": 1, "w": 23, "x": 0, "y": 26 } }
   ]
  },
  {
   "title": "Data Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 23, "x": 0, "y": 2 } },
    {
     "title": "Tile $tile . P$pacman: Data Rate (10s Mean)",
     "type": "timeseries",
     "description": "Mean over 10s of data rates (expressed as data packet count per second) by tile. Y-axis is log base 2. Yellow / Red thresholds = 5k / 50k",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "T$tile P$pacman: IO Channel Data Rate (10s Mean)",
     "type": "piechart",
     "description": "Each tile has 4 Input-Output (IO) channels through which data is transmitted. For a given pacman each IO_channel is uniquely numbered from 1 to 32. The pie chart shows the percentage distribution of data transmitted across the 4 IO_channels for the chosen tile. The text shows the 10s Mean Data Rate (expressed as packet count per second) and the unique IO_channel number. There are no threshold indications",
     "gridPos": { "h": 13, "w": 5, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_chip",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Chip $focus_chip . Tile $tile . P$pacman: Data Rate for Chip $focus_chip (10s Mean)",
     "type": "timeseries",
     "description": "Mean over 10s of data rates (expressed as data packet count per second) by chip. Y-axis is log base 2. Yellow / Red thresholds = 100 / 1k",
     "gridPos": { "h": 10, "w": 6, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates_per_chip",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 23, "x": 0, "y": 16 } }
   ]
  },
  {
   "title": "Hit Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tile $tile . P$pacman: Hit Count over 5m by Chip",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 }
    },
    {
     "title": "T$tile . P$pacman: Lowest Chip Pixel Count",
     "type": "table",
     "description": "Highest 100 Data Rates over the last 5m (expressed as # packets per second) by pixel for the chosen tile. Each value is a 10s Mean. Yellow / Red thresholds = 1 / 5 p/s",
     "gridPos": { "h": 11, "w": 5, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Focus Chip $focus_chip  T$tile . P$pacman: Hit Count",
     "type": "timeseries",
     "description": "Mean over 10s of data rates (expressed as data packet count per second) by chip. Y-axis is log base 2. Yellow / Red thresholds = 100 / 1k",
     "gridPos": { "h": 9, "w": 6, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 22, "x": 0, "y": 14 } }
   ]
  },
  {
   "title": "ADC Mean and RMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 22, "x": 0, "y": 4 } },
    {
     "title": "Tile $tile . P$pacman : ADC Value mean and rms",
     "type": "candlestick",
     "description": "Green bars are centered at Pixel-level Mean ADC value, the top/bottom of the bars are at Mean +/- RMS. All values are calculated over a 10s window.  Red thresholds are <5 or > 254. Yellow threshold is  > 250",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 27, "w": 4, "x": 7, "y": 5 },
     "options": {
      "content": "<img src=https://portal.nersc.gov/project/dune/data/2x2/DQM/PixelMaps/RealTime/iog_${pacman}_mean.png height=\"1000\" width=\"450\"/>\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "T$tile . P$pacman: Top 100 Pixel ADC Mean (5m Max)",
     "type": "table",
     "description": "These are the highest 100 ADC 10s mean values recorded over the last 5m. ADC values are recorded using 8 bits. A value of 255 indicates the ADC maxed out, which could mean we're missing information. This could require an expert to reset the threshold.  Yellow / Red thresholds = 250 / 254",
     "gridPos": { "h": 27, "w": 4, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 27, "w": 4, "x": 16, "y": 5 },
     "options": {
      "content": "<img src=https://portal.nersc.gov/project/dune/data/2x2/DQM/PixelMaps/RealTime/iog_${pacman}_rms.png height=\"1000\" width=\"450\"/>\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Pixel ADC RMS (5m Max) - P$pacman . Tile $tile",
     "type": "table",
     "description": "These are the highest ADC 10s RMS values recorded over a 5m window for the chosen tile",
     "gridPos": { "h": 27, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 6, "x": 0, "y": 16 } },
    {
     "title": "Tile $tile P$pacman: ADC Mean Distribution Pixel Level",
     "type": "histogram",
     "description": "Histogram shows distribution of Pixel-level ADC 10s mean values over the global time window. The bucket size is 1. ADC values are recorded using 8 bits. A value of 255 indicates the signal maxed out. Consistent 255 values (or consistent values below 5) may mean the threshold is set too high (or too low). Both problematic threshold cases could result in missing information. ",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 22, "x": 0, "y": 32 } },
    { "gridPos": { "h": 2, "w": 8, "x": 0, "y": 34 } },
    {
     "title": "FOCUS CHIP $focus_chip PANELS ",
     "type": "text",
     "gridPos": { "h": 2, "w": 9, "x": 11, "y": 34 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Focus Chip $focus_chip . Tile $tile . P$pacman Tile $tile : ADC Value mean and rms",
     "type": "candlestick",
     "description": "Green bars are centered at Pixel-level Mean ADC value, the top/bottom of the bars are at Mean +/- RMS. All values are calculated over a 10s window.  Red thresholds are <5 or > 254. Yellow threshold is  > 250",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 36 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Focus Chip $focus_chip . Tile $tile P$pacman: ADC Mean Distribution Pixel Level",
     "type": "histogram",
     "description": "Histogram shows distribution of Pixel-level ADC 10s mean values over the global time window. The bucket size is 1. ADC values are recorded using 8 bits. A value of 255 indicates the signal maxed out. Consistent 255 values (or consistent values below 5) may mean the threshold is set too high (or too low). Both problematic threshold cases could result in missing information. ",
     "gridPos": { "h": 11, "w": 5, "x": 6, "y": 36 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" }
       ]
      }
     ]
    },
    {
     "title": "Focus Chip $focus_chip: ADC Mean by Pixel (10s Mean)",
     "type": "timeseries",
     "description": "Pixel-level Mean ADC values. All values are calculated over a 10s window.  Red thresholds are <5 or > 254. Yellow threshold is  > 250",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 36 },
     "targets": [
      {
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Focus Chip $focus_chip: ADC RMS by Pixel (10s Mean)",
     "type": "timeseries",
     "description": "Pixel-level ADC RMS values calculated over 10s window.",
     "gridPos": { "h": 11, "w": 5, "x": 18, "y": 36 },
     "targets": [
      {
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "chip::tag", "operator": "=~", "value": "/^$focus_chip$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 11, "x": 0, "y": 47 } }
   ]
  },
  {
   "title": "Invalid Parity Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 5 } },
    {
     "title": "Tile $tile . P$pacman: Mean Invalid % (10s Mean)",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": " invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      },
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman : Top Pixel Invalid Rate (5m Max)",
     "type": "table",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. The numbers in this panel are the maximum 10s mean invalid rates measured over the last 5m.  Rates are expressed as # packet per second per second. Yellow threshold is 0.1, Red threshold is 0.2.",
     "gridPos": { "h": 23, "w": 4, "x": 7, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "T$til3 P$pacman: IO Channel Invalid Parity Rate (10s Mean)",
     "type": "piechart",
     "description": "Each tile has 4 Input-Output (IO) channels through which data is transmitted. For a given pacman each IO_channel is uniquely numbered from 1 to 32. The pie chart shows the percentage distribution of invalid parity data transmitted across the 4 IO_channels for the chosen tile. The text shows the 10s Mean Data Rate (expressed as packet count per second) and the unique IO_channel number. There are no threshold indications",
     "gridPos": { "h": 12, "w": 5, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates_per_chip",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 4, "x": 0, "y": 17 } },
    {
     "title": "Tile $tile . P$pacman: Invalid Rate (10s Mean)",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity Rate is expressed as # invalid packets per second by pixel = sum (invalid parity) / sum (total) for each 10s interval. Y-axis is log base 2. Yellow/Red thresholds =",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 6, "x": 15, "y": 18 } },
    { "gridPos": { "h": 2, "w": 21, "x": 0, "y": 29 } }
   ]
  },
  {
   "title": "Configuration Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 6 } },
    {
     "title": "Tile $tile . P$pacman: Config Rate (1s Mean)",
     "type": "timeseries",
     "description": "Configuration Rate: mean over 1s interval. Config packets should only appear while configuring ADCs. In a normal run mode, the appearance of configuration packets indicates a problem, such as a misconfigured chip or bits that flipped in transmission. Y-axis is log base 2. Thresholds are set for normal run mode as Yellow / Red = .1 p/s / .2 p/s",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile: Top 100 Pixel Packets (2m Max)",
     "type": "table",
     "description": "Configuration Rate: Max Config Rate over the last 5m.  Config packets should only appear while configuring ADCs. In a normal run mode, the appearance of configuration packets indicates a problem, such as a misconfigured chip or bits that flipped in transmission. Thresholds are set for normal run mode as Yellow / Red = .1 p/s / .2 p/s",
     "gridPos": { "h": 15, "w": 5, "x": 7, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "2m" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: IO Channel Config Count (Max over last 10s)",
     "type": "table",
     "description": "Each tile has 4 io channels. Which channel will be used by a particular chip is decided by the Hydra Network. This panel indicates the configuration rate by IO channel for the last 10s interval (per io channel, per tile) ",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "total 1",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FIFO Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 7 } },
    {
     "title": "Tile $tile . P$pacman: Shared FIFO > 1/2 (10s Mean)",
     "type": "barchart",
     "description": "FIFO > 1/2 is the fraction of times the FIFO was more than half full divided by the total number of observations over a 10s window. \"Shared\" FIFO is calculated at the chip level. This graph shows the mean chip level ratio for the chosen tile. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman:  Top 100: Shared FIFO > 1/2  (5m Max)",
     "type": "table",
     "description": "FIFO > 1/2 is the fraction of times a particular chip's FIFO was more than half full but not completely full divided by the total number of observations in a 1s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 1s ratios over the last 5m. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 11, "w": 4, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman:  Shared FIFO FULL (10s Mean)",
     "type": "barchart",
     "description": "FIFO Full is the fraction of times the FIFO was full divided by the total number of observations over a 10s window. \"Shared\" FIFO is calculated at the chip level. This graph shows the mean chip level ratio for the chosen tile. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 7, "w": 6, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Top chips: Shared FIFO Full  (5m Max)",
     "type": "table",
     "description": "FIFO Full is the fraction of times a particular chip's FIFO was full divided by the total number of observations in a 1s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 1s ratios over the last 5m.",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "T$tile . P$pacman: Top Pixel Rates (5m Max)",
     "type": "table",
     "description": "Highest 100 Data Rates over the last 5m (expressed as # packets per second) by pixel for the chosen tile. Each value is a 10s Mean. Yellow / Red thresholds = 1 / 5 p/s",
     "gridPos": { "h": 11, "w": 3, "x": 20, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman: IO Channel Shared FIFO > 1/2 (10s Max)",
     "type": "table",
     "description": "Each tile has 4 Input-Output (IO) channels through which data is transmitted. For a given pacman each IO_channel is uniquely numbered from 1 to 32. This table lists the FIFO > 1/2 packet rate by IO_channel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman: IO Channel Shared FIFO Full (10s Max)",
     "type": "table",
     "description": "Each tile has 4 Input-Output (IO) channels through which data is transmitted. For a given pacman each IO_channel is uniquely numbered from 1 to 32. This table lists the FIFO Full packet rate by IO_channel",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 1, "w": 21, "x": 0, "y": 19 } },
    {
     "title": "Tile $tile . P$pacman: Local FIFO > 1/2 (10s Mean)",
     "type": "barchart",
     "description": "FIFO > 1/2 is the fraction of times the FIFO was more than 1/2 full but less than completely full divided by the total number of observations over a 10s window. \"Local\" FIFO is calculated at the pixel level. This graph shows the mean pixel level ratio for the chosen tile. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Top 100: Local FIFO > 1/2  (5m Max)",
     "type": "table",
     "description": "FIFO > 1/2 is the fraction of times a particular pixel's FIFO was more than half full but not completely full divided by the total number of observations in a 1s window. \"Local\" FIFO is calculated at the pixel level. This filter table lists the pixels with the highest 1s ratios over the last 5m. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 10, "w": 4, "x": 7, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Local FIFO Full (10s Mean)",
     "type": "barchart",
     "description": "FIFO Full is the fraction of times the FIFO was full divided by the total number of observations over a 10s window. \"Local\" FIFO is calculated at the pixel level. This graph shows the mean pixel level ratio for the chosen tile. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 7, "w": 7, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Full",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
       ]
      }
     ]
    },
    {
     "title": "Tile $tile . P$pacman: Top Pixels: Local FIFO Full  (5m Max)",
     "type": "table",
     "description": "FIFO Full is the fraction of times a particular pixel's FIFO was full divided by the total number of observations in a 1s window. \"Local\" FIFO is calculated at the pixel level. This filter table lists the pixels with the highest 1s ratios over the last 5m. Yellow / Red Threshold = 0.1 / 0.2",
     "gridPos": { "h": 10, "w": 4, "x": 19, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" },
        { "params": [ "channel::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman: IO Channel Local FIFO > 1/2 (10s Max)",
     "type": "table",
     "description": "Each tile has 4 Input-Output (IO) channels through which data is transmitted. For a given pacman each IO_channel is uniquely numbered from 1 to 32. This table lists the FIFO > 1/2 packet rate by IO_channel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    {
     "title": "P$pacman: IO Channel Local FIFO Full (10s Max)",
     "type": "table",
     "description": "Each tile has 4 Input-Output (IO) channels through which data is transmitted. For a given pacman each IO_channel is uniquely numbered from 1 to 32. This table lists the FIFO Full packet rate by IO_channel",
     "gridPos": { "h": 4, "w": 7, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
        { "condition": "AND", "key": "tile_id::tag", "operator": "=~", "value": "/^$tile$/" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 2, "w": 21, "x": 0, "y": 31 } },
    { "gridPos": { "h": 1, "w": 5, "x": 7, "y": 33 } }
   ]
  },
  {
   "title": "Hydra-network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 39, "w": 6, "x": 0, "y": 8 } },
    { "gridPos": { "h": 1, "w": 5, "x": 0, "y": 47 } },
    { "gridPos": { "h": 1, "w": 5, "x": 0, "y": 48 } }
   ]
  },
  {
   "title": "Pixel Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 31, "w": 7, "x": 0, "y": 9 },
     "options": {
      "content": "<img src=https://portal.nersc.gov/project/dune/data/2x2/DQM/PixelMaps/RealTime/iog_${pacman}_rate.png height=\"1100\" width=\"600\"/>\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 31, "w": 7, "x": 7, "y": 9 },
     "options": {
      "content": "<img src=https://portal.nersc.gov/project/dune/data/2x2/DQM/PixelMaps/RealTime/iog_${pacman}_mean.png height=\"1100\" width=\"600\"/>\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 31, "w": 7, "x": 14, "y": 9 },
     "options": {
      "content": "<img src=https://portal.nersc.gov/project/dune/data/2x2/DQM/PixelMaps/RealTime/iog_${pacman}_rms.png height=\"1100\" width=\"600\"/>\n"
     },
     "targets": [
      {}
     ]
    },
    { "gridPos": { "h": 1, "w": 9, "x": 11, "y": 40 } }
   ]
  }
 ]
}