{
 "title": "Shifter",
 "time": { "from": "2024-10-03T14:39:21.851Z", "to": "2024-10-03T14:52:09.293Z" },
 "templating": {
  "list": [
   { "name": "pacman", "query": "1,2,3,4" }
  ]
 },
 "panels": [
  { "title": "System Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Data Rate by Pacman (10s mean)", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 } },
  { "title": "Sync Pulse", "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 } },
  { "title": "Processor Temperature", "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 } },
  {
   "title": "Power Alerts: Are VDDD and IDDD within Threshold (blue \"yes\", red \"no\")",
   "type": "text",
   "description": "These boxes check to see if VDDD and IDDD are within threshold ranges. Digital voltage (VDDD) is supplied to digital side of ADC to power data transfer to and from chips. Acceptable range is (1.5 to 1.8V) for all pacmen except P5-P6 whose acceptable range is (1.1 to 1.3V) - the exception is needed because of differences between versions of the chips used (V2A versus V2B). Similarly IDDD is current supplied to the digital side. Thresholds are 350-750mA for all pacmen.  ",
   "gridPos": { "h": 1, "w": 8, "x": 15, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "P1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         1500,
         1800
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "type": "threshold"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         350,
         750
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "B",
     "type": "threshold"
    },
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  {
   "title": "P2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "P3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "P4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "Power Alerts: Absolute Value (Change in VDDD over last 1h) < 10%  (blue \"yes\", red \"no\")",
   "type": "text",
   "description": "Is the absolute value of the change in VDDD over the last hour less than 10%? Blue is yes. Red is no.  Digital voltage (VDDD) is supplied to digital side of ADC to power data transfer to and from chips. ",
   "gridPos": { "h": 1, "w": 8, "x": 15, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Data Rate (10s mean)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_statuses_rates",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "P1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "P2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "IDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         1500,
         1800
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "type": "threshold"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         350,
         750
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "B",
     "type": "threshold"
    },
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  {
   "title": "P3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "IDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         1500,
         1800
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "type": "threshold"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         350,
         750
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "B",
     "type": "threshold"
    },
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  {
   "title": "P4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 1, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "IDDD",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         1500,
         1800
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "type": "threshold"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         350,
         750
        ],
        "type": "within_range"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "B",
     "type": "threshold"
    },
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  { "title": "Data File Size and Location", "gridPos": { "h": 5, "w": 10, "x": 5, "y": 10 } },
  { "title": "Pacman Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "P$pacman: Data Rate (10s Mean) by Tile",
   "type": "timeseries",
   "description": "Mean over 10s of data rates (expressed as packet count per second) by tile. Y-axis is log base 2. Yellow/Red thresholds = 5kps / 50kps",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "tile_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_statuses_rates",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "P$pacman: ADC Mean and RMS by Tile (10s Mean)",
   "type": "text",
   "description": "Green bars are centered at Pixel-level Mean ADC value, the top/bottom of the bars are at Mean +/- RMS. All values are calculated over a 10s window.  Red thresholds are < 5 or > 254. Yellow threshold is 250",
   "gridPos": { "h": 1, "w": 5, "x": 7, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "P$pacman: ADC Pixel Distribution (1s Mean)",
   "type": "text",
   "description": "Histogram shows distribution of Pixel-level ADC mean values over the global time window. The bucket size is 1. ADC values are recorded using 8 bits. A value of 255 indicates the signal maxed out. Consistent values at 255 (or below 5) may indicate thresholds are set too high (or low) .  All mean values in this histogram are calculated over a 10s window",
   "gridPos": { "h": 1, "w": 4, "x": 15, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Pixel Data Rates P$pacman",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 20, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tile 1",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 17 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Tile 2",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 17 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Tile 1",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 17 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 2",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "description": "Highest 100 pixel data packet rates (expressed as # packets per second - p/s) within a given pacman. Each value represents the  mean rate recorded over the last 30s. Yellow/Red thresholds = 1/5 p/s",
   "gridPos": { "h": 18, "w": 3, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "chip::tag" ], "type": "tag" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "io_channel::tag" ], "type": "tag" },
      { "params": [ "channel::tag" ], "type": "tag" }
     ],
     "measurement": "top_data_rate_channels",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 3",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 24 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Tile 4",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 24 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "Tile 3",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 24 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 4",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 24 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 5",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 31 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "5" }
     ]
    }
   ]
  },
  {
   "title": "Tile 6",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 31 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "6" }
     ]
    }
   ]
  },
  {
   "title": "Tile 5",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 31 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 6",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 31 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Pixel ADC Values P$pacman",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 20, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "description": "The highest 100 ADC mean values recorded over the last 30s. ADC values are recorded using 8 bits. A value of 255 indicates the ADC maxed out, which could mean we're missing information. This could require an expert to reset the threshold.  Yellow / Red thresholds = 250 / 254",
   "gridPos": { "h": 16, "w": 3, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "chip::tag" ], "type": "tag" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "io_channel::tag" ], "type": "tag" },
      { "params": [ "channel::tag" ], "type": "tag" }
     ],
     "measurement": "top_adc_mean_channels",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 7",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 38 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Tile 8",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 38 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "Tile 7",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 38 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 8",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 38 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "8" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 9",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 45 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "9" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "9" }
     ]
    }
   ]
  },
  {
   "title": "Tile 10",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 45 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "rms",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_rms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile_id::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Tile 9",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 45 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "9" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  {
   "title": "Tile 10",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 45 },
   "targets": [
    {
     "alias": "mean",
     "measurement": "packet_adc_per_channel",
     "select": [
      [
       { "params": [ "adc_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tile_id::tag", "operator": "=", "value": "10" },
      { "condition": "AND", "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" }
     ]
    }
   ]
  },
  { "gridPos": { "h": 1, "w": 20, "x": 0, "y": 52 } },
  {
   "title": "P$pacman: VDDD",
   "type": "timeseries",
   "description": "Digital voltage supplied to digital side of ADC to power data transfer to and from chips. Acceptable range is (1.6 to 1.7V) for all pacmen except P5-P6 whose acceptable range is (1.15 to 1.25V) - the exception is needed because of differences between versions of the chips used (V2A versus V2B)",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "vddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  { "title": "P$pacman: VDDA", "gridPos": { "h": 6, "w": 5, "x": 5, "y": 53 } },
  {
   "title": "P$pacman: IDDD",
   "type": "timeseries",
   "description": "Current supplied to digital side of ADC to power data transferred to and from the chip. Acceptable range is (400-700mA)",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "iddd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  {
   "title": "P$pacman: IDDA",
   "type": "timeseries",
   "description": "Current supplied to the analogue side of the ADC to power charge collection from pixel to the chip. Acceptable range for most pacmen (150-475mA), but P5 and P6 are distinct (because of distinct models of chips/pacmen) with thresholds (60-110)",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "alias": "T1",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "T2",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "T3",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "T4",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "T5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "T6",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "T7",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "T8",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "io_group::tag" ], "type": "tag" },
      { "params": [ "tile::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pacman_power",
     "select": [
      [
       { "params": [ "idda" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io_group::tag", "operator": "=~", "value": "/^$pacman$/" },
      { "condition": "AND", "key": "tile::tag", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  { "gridPos": { "h": 10, "w": 4, "x": 1, "y": 59 } },
  { "gridPos": { "h": 2, "w": 24, "x": 0, "y": 69 } }
 ]
}