{
 "title": "1 System",
 "time": { "from": "2024-02-20T18:46:20.483Z", "to": "2024-02-20T19:12:31.912Z" },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Packet Rate (10s mean) & Beam Trigger",
     "type": "timeseries",
     "description": "Total (data+config+test) packet rate count per 1s (shown as mean value over 10s). Beam trigger signal indicated by white bar.  An increase in the packet rate should coincide with the arrival of the beam. Y-axis is log base 2. Red threashold = 60k packets/s. ",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Invalid Parity % - System (10s mean)",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Configuration % - System (10s mean)",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ADC Mean and RMS (10s mean)",
     "type": "candlestick",
     "description": "The green bars in the graph below are centered at the mean ADC value. The top/bottom of each bar is at mean +/- RMS. Mean and RMS values are calculated over a 10s window. ",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "title": "Pacman 1", "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 } },
    {
     "title": "ALL GAUGES SHOW MAX OR MEAN VALUES (see title) OVER THE LAST 15 MINUTES",
     "type": "text",
     "gridPos": { "h": 1, "w": 7, "x": 0, "y": 9 }
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "alias": "Mean Total Packets/s",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max Invalid Packet/s",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Max Config Packets/s",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Max ADC Value",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_total",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Max ADC RMS",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_total",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 19, "x": 2, "y": 16 } },
    {
     "title": "Shared FIFO > 1/2 and Full (10s means)",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. \"Shared\" FIFO is calculated at the chip level. This graph shows the mean chip level ratio for the entire system. This stacked bar chart shows the FIFO > 1/2 (but not completely full) as a blue bar. On top of the blue bar is FIFO full shown as a red bar",
     "gridPos": { "h": 8, "w": 6, "x": 1, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Local FIFO > 1/2 and Full (10s means)",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. \"Shared\" FIFO is calculated at the chip level. This graph shows the mean chip level ratio for the entire system. This stacked bar chart shows the FIFO > 1/2 (but not completely full) as a blue bar. On top of the blue bar is FIFO full shown as a red bar",
     "gridPos": { "h": 8, "w": 6, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "title": "Sync Packets", "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 } },
    {
     "title": "Top 100 Chip Packets (15m Mean)",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_channel::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel Packets (15m Mean)",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 }
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "alias": "Max Shared FIFO > 1/2 %",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Max Shared FIFO Full %",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Max Local FIFO > 1/2 %",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Max Local FIFO Full %",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "local_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 19, "x": 0, "y": 31 } },
    { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 0, "y": 32 } }
   ]
  },
  {
   "title": "Total Packet Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pacman Granular Packet Rate (pcs / 0.1s) & Beam Trigger (both for the last 3m)",
     "type": "text",
     "description": "Total (data+config+test) packet rate count in 0.1s intervals. Beam trigger signal indicated by white bar.  An increase in the packet rate should coincide with the arrival of the beam. Y-axis is log base 2. Red threashold = 50k packets/s. When running live, the time window for these panels is 3 minutes. ",
     "gridPos": { "h": 1, "w": 8, "x": 0, "y": 2 },
     "options": {
      "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "Pacman Packet Rate (10s Mean)",
     "type": "text",
     "description": "Total (data+config+test) packet rate per 1s expressed as mean over the last 1 values. Y-axis is log base 2. Red threashold = 50k packets/s",
     "gridPos": { "h": 1, "w": 8, "x": 9, "y": 2 },
     "options": {
      "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "Top 100 Chip Packets (15m Mean)",
     "type": "table",
     "gridPos": { "h": 16, "w": 3, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 100 Pixel Packets (15m Mean)",
     "gridPos": { "h": 16, "w": 4, "x": 20, "y": 2 }
    },
    {
     "title": "Pacman 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 4",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "P1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 9, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "P2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 11, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "P3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 13, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "P4",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 15, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 17, "x": 0, "y": 10 } },
    {
     "title": "Pacman 5",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "5" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 6",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "6" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 7",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "7" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 8",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "8" }
       ]
      }
     ]
    },
    {
     "title": "P5",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 9, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "5" }
       ]
      }
     ]
    },
    {
     "title": "P6",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 11, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "6" }
       ]
      }
     ]
    },
    {
     "title": "P7",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 13, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "7" }
       ]
      }
     ]
    },
    {
     "title": "P8",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 2, "x": 15, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "8" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 21, "x": 0, "y": 18 } }
   ]
  },
  {
   "title": "Invalid and Configuration Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 0, "y": 3 } },
    {
     "title": "Invalid Parity % - System (10s mean)",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Top 100 Chips Invalid Rate (15m Mean)",
     "type": "table",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. The numbers in this panel are the  maximum value over the chosen time window (typically 15m). Yellow threshold is 1k, Red threshold is 10k.",
     "gridPos": { "h": 10, "w": 5, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "data_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Configuration % - System (10s mean)",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 10, "w": 7, "x": 13, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 100 Chips Config Rate (15m Max)",
     "type": "table",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. The numbers in this panel are the  maximum value over the chosen time window (typically 15m). Yellow threshold is 1k, Red threshold is 10k.",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" }
       ],
       "measurement": "config_statuses_rates_per_channel",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Invalid Parity % by Pacman (10s mean)",
     "type": "text",
     "gridPos": { "h": 1, "w": 11, "x": 0, "y": 14 }
    },
    {
     "title": "Configuration % by Pacman",
     "type": "text",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over a pacman. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 1, "w": 11, "x": 13, "y": 14 }
    },
    {
     "title": "P1",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "P2",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "P3",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "P4",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "invalid",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "io_channel::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "invalid_parity" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_channel::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "P1",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 7, "w": 2, "x": 13, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "P2",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 7, "w": 2, "x": 15, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "P3",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 7, "w": 2, "x": 17, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "P4",
     "type": "timeseries",
     "description": "Configuration % = sum (config packet) / sum (total packet) for each 1s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%",
     "gridPos": { "h": 7, "w": 2, "x": 19, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "config_statuses_rates",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "io_channel::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 17, "x": 0, "y": 22 } },
    { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 0, "y": 23 } }
   ]
  },
  {
   "title": "ADC Mean and RMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ADC Value Mean and RMS (10s)",
     "type": "text",
     "description": "The Green bars are centered at the mean ADC value, the top/bottom of the bars are at Mean +/- RMS. All values are calculated over a 10s window. ",
     "gridPos": { "h": 1, "w": 22, "x": 0, "y": 4 }
    },
    {
     "title": "Pacman 1",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 2",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 3",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 4",
     "type": "candlestick",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "rms",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "ADC Value Histogram (over global time window)",
     "type": "text",
     "description": "The histogram shows the distribution of ADC values over the global time window (typically 15m). The bucket size is 1",
     "gridPos": { "h": 1, "w": 20, "x": 0, "y": 12 }
    },
    {
     "title": "Pacman 1",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 2",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 3",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Pacman 4",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "alias": "mean",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "ADC Value - raw data (1s intervals)",
     "type": "text",
     "description": "RMS values are calculated over a 10s window. ",
     "gridPos": { "h": 1, "w": 20, "x": 0, "y": 20 }
    },
    {
     "title": "P1",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "P2",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "P3",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "P4",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "ADC Value RMS - raw data (1s intervals)",
     "type": "text",
     "description": "RMS values are calculated over a 10s window. ",
     "gridPos": { "h": 1, "w": 20, "x": 0, "y": 26 }
    },
    {
     "title": "P1",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "P2",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "P3",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "P4",
     "type": "timeseries",
     "description": "Invalid parity indicates that bits flipped at some point in the packet's transmission from chip to pacman. Invalid Parity % = sum (invalid parity) / sum (total) for each 10s interval over entire system. Y-axis is log base 2. Yellow threshold is 1%, Red threshold is 10%.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "packet_adc_per_channel",
       "select": [
        [
         { "params": [ "adc_rms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 0, "y": 32 } },
    { "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 33 } }
   ]
  },
  {
   "title": "FIFO Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 23, "x": 0, "y": 5 } },
    {
     "title": "Shared FIFO > 1/2 and Full (10s Mean)",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. \"Shared\" FIFO is calculated at the chip level. This graph shows the mean chip level ratio for the entire system. This stacked bar chart shows the FIFO > 1/2 (but not completely full) as a blue bar. On top of the blue bar is FIFO full shown as a red bar",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 100: Shared FIFO > 1/2  (1s Max)",
     "type": "table",
     "description": "FIFO > 1/2 is the fraction of times a particular chip's FIFO was more than half full (but not completely full) divided by the total number of observations in a 10s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 10s ratios over the dashboard's chosen time window (typically 15m).",
     "gridPos": { "h": 13, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 100: Shared FIFO Full   (1s Max)",
     "type": "table",
     "description": "FIFO Full is the fraction of times a particular chip's FIFO was full divided by the total number of observations in a 10s window. \"Shared\" FIFO is calculated at the chip level. This filter table lists the chips with the highest 10s ratios over the dashboard's chosen time window (typically 15m).",
     "gridPos": { "h": 13, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "tile_id::tag" ], "type": "tag" },
        { "params": [ "io_group::tag" ], "type": "tag" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 100: Local FIFO > 1/2  (15m Max)",
     "gridPos": { "h": 13, "w": 4, "x": 16, "y": 6 }
    },
    {
     "title": "Top 100: Local FIFO Full   (15m Max)",
     "gridPos": { "h": 13, "w": 4, "x": 20, "y": 6 }
    },
    {
     "title": "Shared FIFO > 1/2 and FULL (10s Means)",
     "type": "text",
     "gridPos": { "h": 1, "w": 23, "x": 0, "y": 19 }
    },
    {
     "title": "P1",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the mean chip level ratio for Pacman 1. The stacked bars show the FIFO > 1/2 (but not completely full) as a blue bar, with the FIFO full on top of it as a red bar",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "P2",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the mean chip level ratio for Pacman 1. The stacked bars show the FIFO > 1/2 (but not completely full) as a blue bar, with the FIFO full on top of it as a red bar",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "P3",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the mean chip level ratio for Pacman 1. The stacked bars show the FIFO > 1/2 (but not completely full) as a blue bar, with the FIFO full on top of it as a red bar",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "P4",
     "type": "barchart",
     "description": "FIFO > 1/2 (or Full) is the fraction of times the FIFO was more than half full (or Full) divided by the total number of observations over a 10s window. It is calculated at the chip level. This graph shows the mean chip level ratio for Pacman 1. The stacked bars show the FIFO > 1/2 (but not completely full) as a blue bar, with the FIFO full on top of it as a red bar",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "> 1/2",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "FULL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 } },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "1s Max FIFO > 1/2",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "1s Max FIFO Full",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "1s Max FIFO > 1/2",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "1s Max FIFO Full",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "1s Max FIFO > 1/2",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "more_half_full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "1s Max FIFO Full",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shared_fifo_statuses",
       "select": [
        [
         { "params": [ "full" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "tile_id::tag", "operator": "=", "value": "1" },
        { "condition": "AND", "key": "io_group::tag", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 36 } }
   ]
  },
  {
   "title": "Sync Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 0, "y": 6 } },
    { "title": "Sync Packets", "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 } },
    { "title": "Dashboards and Links", "gridPos": { "h": 9, "w": 2, "x": 21, "y": 7 } }
   ]
  },
  { "title": "Sync dT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 } }
 ]
}